# Generated by Django 5.2.10 on 2026-01-18 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('encrypted_filename', models.CharField(max_length=255, unique=True)),
                ('encrypted_file', models.FileField(upload_to='vault/encrypted/')),
                ('file_size', models.BigIntegerField(help_text='Size of original file in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
